version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db
    ports:
      - '3000:3000' # Forward Next.js port
      - '3001:3001' # Forward backup port

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
      POSTGRES_DB: trading_app_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-nexastrade:/var/lib/postgresql/data

volumes:
  postgres-data-nexastrade:
